Add support for Heatmap panels
grafana-tools/sdk pull request #122
Opened 2021-01-19 08:49 UTC by K-Phoen

Hi!

In this PR, I add support for Heatmap panels: https://grafana.com/docs/grafana/v6.7/getting-started/intro-histograms/#heatmaps
They're available since v6.7 at least (not sure about prior versions)

2021-02-28 20:35 UTC, GiedriusS requested changes
LGTM, just a few suggestions on the types in your structs!

2021-02-28 20:35 UTC, GiedriusS commented on panel.go
> +			Max         *float64 `json:"max"`
I think this is a string. In one of my example dashboards I got:
```
      "yAxis": {
        "decimals": 3,
        "format": "short",
        "logBase": 1,
        "max": "100",
        "min": "0",
        "show": true,
        "splitFactor": null
      },
  ```

2021-02-28 20:35 UTC, GiedriusS commented on panel.go
> +			Min         *float64 `json:"min"`
Ditto.

2021-02-28 20:35 UTC, GiedriusS commented on panel.go
> +		XBucketSize   *float64 `json:"xBucketSize"`
I think this is a string at least on 6.7.1:
```
      "xAxis": {
        "show": true
      },
      "xBucketNumber": 0,
      "xBucketSize": "2",
      "yAxis": {
  ```

2021-02-28 20:35 UTC, GiedriusS commented on panel.go
> +			Min         *float64 `json:"min,omitempty"`
This is correct :+1:

2021-03-01 10:09 UTC, GiedriusS approved these changes
:heart:

2021-03-01 10:09 UTC, merged

2021-03-01 10:11 UTC, K-Phoen commented
Thanks for the careful review and merge @GiedriusS :muscle: